# Generated by Django 5.1.12 on 2025-09-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('member', 'Member'), ('viewer', 'Viewer'), ('guest', 'Guest')], default='member', help_text='Role to assign to the invited user', max_length=20),
        ),
    ]
