# Generated by Django 5.1.12 on 2025-09-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_first_name_invitation_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
