# Generated by Django 5.1.12 on 2025-09-11 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_make_names_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status', 'is_deleted'], name='invitations_status_989cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invited_by', 'status', 'is_deleted'], name='invitations_invited_360dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['is_deleted', 'created_at'], name='invitations_is_dele_890ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status', 'expires_at'], name='invitations_status_0460ba_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status', 'is_deleted'], name='invitations_email_fb9406_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status', 'accepted_at'], name='invitations_status_6cd422_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['role', 'is_deleted'], name='invitations_role_82638b_idx'),
        ),
    ]
