# Generated by Django 5.1.12 on 2025-09-10 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
    ]
