volumes:
  backend_local_postgres_data: {}
  backend_local_postgres_data_backups: {}
  backend_local_redis_data: {}

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    image: backend_local_nginx
    depends_on:
      - django
      - mailpit
    ports:
      - '8000:80'
    restart: unless-stopped

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    expose:
      - '8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    volumes:
      - backend_local_postgres_data:/var/lib/postgresql/data
      - backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    expose:
      - "8025"

  redis:
    image: docker.io/redis:6
    volumes:
      - backend_local_redis_data:/data

  celeryworker:
    <<: *django
    image: backend_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: backend_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: backend_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  frontend:
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
    image: backend_local_frontend
    depends_on:
      - django
    volumes:
      - ./frontend:/app:z
      - /app/node_modules  # Anonymous volume for node_modules
    env_file:
      - ./.envs/.local/.frontend
    ports:
      - '5173:5173'  # Vite's default port
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port 5173
