# Generated by Django 5.1.12 on 2025-10-13 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_pet_petactivity'),
        ('users', '0004_alter_user_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was soft deleted', null=True)),
                ('invitee_email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], help_text='Role to be assigned upon acceptance (PARENT or CHILD only)', max_length=20)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique token for invitation acceptance link', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the invitation', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires (7 days from creation)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='Family the invitee is being invited to join', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='shared.family')),
                ('inviter', models.ForeignKey(help_text='User who sent this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_invit_token_a8a224_idx'), models.Index(fields=['status', 'expires_at'], name='users_invit_status_d705f9_idx'), models.Index(fields=['family', 'status'], name='users_invit_family__3adc50_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('family', 'invitee_email'), name='unique_pending_invitation_per_family_email')],
            },
        ),
    ]
