# Generated by Django 5.1.12 on 2025-09-07 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('code_name', models.CharField(help_text="Unique permission identifier (e.g., 'view_reports')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(blank=True, help_text="Permission category for organization (e.g., 'reporting', 'admin')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is currently active')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this permission expires (optional)', null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context for this permission assignment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is currently active')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this role assignment expires (optional)', null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context for this role assignment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active')),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('resource_type', models.CharField(help_text="Type of resource (e.g., 'article', 'project', 'document')", max_length=100)),
                ('resource_id', models.CharField(help_text='Identifier for the specific resource', max_length=255)),
                ('name', models.CharField(help_text='Human-readable resource name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this resource')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about this resource')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['resource_type', 'name'],
                'unique_together': {('resource_type', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('code_name', models.CharField(help_text="Unique role identifier (e.g., 'content_manager')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable role name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted by users')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted by this role', related_name='roles', to='permissions.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
    ]
