# Generated by Django 5.1.12 on 2025-09-08 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs'),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs'),
        ),
        migrations.AddField(
            model_name='role',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id'),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id'),
        ),
    ]
