# Generated by Django 5.1.12 on 2025-09-10 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_permission_public_id_resource_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True),
        ),
    ]
