#!/bin/bash

set -o errexit
set -o nounset

# Set PYTHONPATH to find Django modules - Ham Dog's brilliant idea #2!
export PYTHONPATH=$PYTHONPATH:/app/backend

exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker -l INFO'
