# Generated by Django 5.1.12 on 2025-10-13 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external API references and URLs', unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Legacy UUID field - will be removed after migration to public_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - if True, record is considered deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(choices=[('appointment', 'Appointment'), ('meeting', 'Meeting'), ('reminder', 'Reminder'), ('other', 'Other')], default='other', help_text='Type of event', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Event start time')),
                ('end_time', models.DateTimeField(help_text='Event end time')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleevent_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='Family this event belongs to', on_delete=django.db.models.deletion.CASCADE, to='shared.family')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Event',
                'verbose_name_plural': 'Schedule Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
